export interface Testimonial {
  name: string;
  city: string;
  text: string;
  stars: number;
  date: string;
  verified?: boolean;
  avatar?: string;
  beforeAfterImage?: string;
}

export const testimonials: Testimonial[] = [
  {
    name: "سلمى",
    city: "القاهرة",
    text: "الحمد لله النتيجة فوق كل توقيع! بشرتي أصبحت نضيفة وناعمة جداً بعد أسبوعين فقط من الاستخدام. المنتج فعلاً سحر! 🌹",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-1.png",
  },
  {
    name: "مريم",
    city: "الإسكندرية",
    text: "بصراحة ما كنت أصدق النتايج بس بعد ما جربته بنفسي! الحبوب والبقع اختفت تماماً وبشرتي عادت لطبيعتها الليليطة. شكراً لكم ❤️",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-2.png",
  },
  {
    name: "ندى",
    city: "الجيزة",
    text: "النتيجة تحفة اللهم بارك، بشرتي بقت ناعمة وصافية جداً والمسام صغرت بشكل ملحوظ. فعلاً السيروم ده سحر!",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-3.png",
  },
  {
    name: "سارة",
    city: "طنطا",
    text: "بعد أسبوعين من الاستخدام بصراحة النتيجة فوق التوقيع! بشرتي أصبحت ناعمة ونضيفة جداً والبقع بدأت تختفي. شكراً لكم على المنتج الرائع والخدمة الممتازة 🌹",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/real-review-1.jpg",
  },
  {
    name: "أمل",
    city: "المنصورة",
    text: "أنا جداً سعيدة بالنتيجة! بشرتي كانت متعبة جداً والآن أصبحت مشرقة ونضيفة. أنصح الجميع بتجربة المنتج فعلاً يستحق كل قرش ✨",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/real-review-2.jpg",
  },
  {
    name: "حبيبة",
    city: "زقازيق",
    text: "بعد ما كنت أستخدم كل شيء ولا نتيجة، جربت السيروم ده وخلاص! بشرتي عادت أفضل من أي وقت مضى. شكراً لكم من القلب 🙏",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/real-review-3.jpg",
  },
  {
    name: "فاطمة",
    city: "أسوان",
    text: "النتيجة مذهلة! الحبوب اختفت تماماً وبشرتي أصبحت ناعمة مثل الطفل. لم أكن أتوقع نتيجة بهذا السرعة! شكراً لكم 💕",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-4.jpg",
  },
  {
    name: "سندس",
    city: "بورسعيد",
    text: "أنا داخله أشكرك بجد ع المجهود ده وان وصلت للنتيجه حلوه و حبها برغم ان انا كنت خلاص يأست بجد شكرا ليكي السيرم اجمل حاجه جبتها ❤️",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-5.jpg",
  },
  {
    name: "لين",
    city: "السويس",
    text: "الحمد لله انو صدفة لقيتكم! المنتج فعلاً رائع ونتايجه حقيقية. بشرتي الآن لا تحتاج إلى أي مكياج أساسي لأنها نضيفة من نفسها ✨",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-6.jpg",
  },
  {
    name: "نور",
    city: "دمياط",
    text: "بعد أسبوع واحد فقط لاحظت الفرق! بشرتي بدأت تتحسن والبقع تتلاشى. الآن بعد ثلاثة أسابيع النتيجة غير واقعية! شكراً لكم 🌹",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-7.jpg",
  },
  {
    name: "دينا",
    city: "كفر الشيخ",
    text: "بصي دي بشرتي أتعدل شويا الحمد لله! بس ف شويا حبوب صغننين أفضل وراهم لحد م همشيهم إن شاء الله 😂❤️",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-8.jpg",
  },
  {
    name: "شروق",
    city: "مطروح",
    text: "النصائح والروتين مع المنتج فعلاً كان الفرق! بشرتي الآن ناعمة ونضيفة والحبوب اختفت تماماً. أنصح الجميع بشدة! 🙏",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-9.jpg",
  },
  {
    name: "سوزان",
    city: "الفيوم",
    text: "أنا جربت كتير منتجات ولا نتيجة، بس هذا المنتج اللي غير حياتي! بشرتي أصبحت مثل مرآة نضيفة. شكراً لكم من أعماق قلبي 💕",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-10.jpg",
  },
  {
    name: "هبة",
    city: "بني سويف",
    text: "الحمد لله لقيت المنتج اللي كنت أبحث عنه من زمان! بشرتي تعافت تماماً والحبوب والبقع اختفت للابد. شكراً لكم على كل شيء ✨",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-11.jpg",
  },
  {
    name: "سما",
    city: "المنيا",
    text: "أنا لست من الناس اللي تكتب تقيمات بسهولة، بس المنتج ده يستحق كل الكلام! النتيجة مذهلة وفوق كل توقيع. شكراً لكم 🌹",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-12.jpg",
  },
  {
    name: "مينه",
    city: "أسيوط",
    text: "بعد شهر كامل من الاستخدام أستطيع أقول بثقة: هذا أفضل منتج جربته في حياتي! بشرتي تغيرت تماماً للأفضل. شكراً لكم 🙏",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-13.jpg",
  },
  {
    name: "رنا",
    city: "سوهاج",
    text: "النتيجة غيرت حياتي! كنت خجولة جداً من بشرتي والآن أخرج بدون مكياج بثقة تامة. المنتج فعلاً معجزة! ❤️",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-14.jpg",
  },
  {
    name: "ندى",
    city: "قنا",
    text: "بصراحة كنت خايفة أجرب المنتج بس بعد ما شفت نتايج صديقتي قررت أجرب وخلاص مآسفت! النتيجة فوق كل توقيع 🌹",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-15.jpg",
  },
  {
    name: "آية",
    city: "الأقصر",
    text: "الحمد لله انو وجدتكم! بشرتي كانت تعاني من حبوب شديدة والآن أصبحت نظيفة تماماً. شكراً لكم على المنتج الرائع والدعم الممتاز ✨",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-16.jpg",
  },
  {
    name: "سلمى",
    city: "الغردقة",
    text: "أنا جداً سعيدة بالنتيجة! بشرتي أصبحت ناعمة ونضيفة والحبوب اختفت تماماً. أنصح كل واحدة تعاني من مشاكل البشرة تجربه 💕",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-17.jpg",
  },
  {
    name: "جومانا",
    city: "العريش",
    text: "بعد ما كنت أضيع آلاف الجنيهات على منتجات لا فائدة منها، لقيت السيروم ده وخلاص الحمد لله النتيجة مذهلة! شكراً لكم 🙏",
    stars: 5,
    date: "2026-04-21",
    verified: true,
    beforeAfterImage: "/reviews/review-18.jpg",
  },
];


